# ------------------------------------------------------------------------------
# Options
# ------------------------------------------------------------------------------
unbind C-b
set -g prefix "C-^"
bind "C-^" send-prefix

set -g default-terminal "screen-256color"
set-option -sa terminal-overrides ",xterm*:Tc"
# set -g default-terminal "$TERM"
# set -ag terminal-overrides ",$TERM:Tc"

set -g mouse on
set -g base-index 1
set -g mode-keys vi
set -s escape-time 0
set -g history-limit 50000
set -g display-time 4000
set -g status-interval 5
set -g status-keys emacs
set -g focus-events on
setw -g aggressive-resize on

# ------------------------------------------------------------------------------
# Keymaps
# ------------------------------------------------------------------------------
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?)(diff)?$'"

bind -n C-w if-shell "$is_vim" "send-keys C-w" "switch-client -Tnavigator"
bind -Tnavigator 'h' select-pane -L
bind -Tnavigator 'j' select-pane -D
bind -Tnavigator 'k' select-pane -U
bind -Tnavigator 'l' select-pane -R

bind -n M-k if-shell "$is_vim" "send-keys M-k" "resize-pane -U 2"
bind -n M-j if-shell "$is_vim" "send-keys M-j" "resize-pane -D 2"
bind -n M-h if-shell "$is_vim" "send-keys M-h" "resize-pane -L 2"
bind -n M-l if-shell "$is_vim" "send-keys M-l" "resize-pane -R 2"

bind . copy-mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle \; send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# ------------------------------------------------------------------------------
# Statusbar
# ------------------------------------------------------------------------------
set -g status-style fg=white,bg=default
set -wg window-status-style fg=white,bg=default
set -wg window-status-current-style fg=blue,bg=default
set -g pane-border-style fg="#535558" 
set -g pane-active-border-style fg="#535558"  
set -g message-style fg=magenta,bg=default
set -g display-panes-active-colour magenta
set -g display-panes-colour magenta
set -g status-right "#[fg=white][#h] %A, %d %b %I:%M %p"
